fixed some bugs be more generic

diff --git a/flattenPaper b/flattenPaper
--- a/flattenPaper
+++ b/flattenPaper
@@ -4,13 +4,14 @@ function help () {
 echo " This script prepares a paper source code to be published to arxiv. It needs to be called with the name of the main .tex file (without extension) that is located in the current directory";
 echo "";
 echo " Usage: flattenPaper texFile pkgPrefix figsDir";
+echo " Example usage: flattenPaper paper casper figs";
 echo " Here, 'texFile' is a .tex file, 'pkgPrefix' the prefix for any private macro files apart from temf-* macros and 'figsDir' the directory in which all figures are contained.";
 echo "";
 echo " Supported source files:";
 echo " - *.tex, *.sty, *.cls, *.clo, *.bib";
 echo "";
 echo " Prerequisites:";
-echo " - all figures must be contained in one folder according to the input paramter 'figs'";
+echo " - all figures must be contained in one folder according to the input parameter 'figs'";
 echo " - different figures must have different names, not only different extensions";
 echo " - packages are loaded without using any additional path";
 echo " - if standalone figures are used together with the standalone package, they must be included with the \includestandalone macro (see standalone package documentation) instead of \input or \include. The filename of the standalone figure must be given without extension, e.g., 'example' instead of 'example.tex' and the files must be contained in a folder called 'figsStandalone'. Additionally, the standalone package option 'mode=build', 'mode=buildmissing' or 'mode=buildnew' must be used";
@@ -18,8 +19,10 @@ echo " - enclose all bib setup lines in the preamble into a beginning line conta
 echo " - no TUD colors must be used outside of figures";
 echo " - if figures include references to anything in the rest of the LaTeX document, they must be included directly in the LaTeX document or by the \input command";
 echo " - if the standalone package is used, all standalone files must be included using the \includestandalone command. This is due to a limitation of latexpand that does not recognize standalone input files.";
+echo " - all custom packages that are not present in a standard LaTeX installation must be present as .sty-files in the current directory or any of its subdirectories.";
 echo "";
 echo " Required tools that must be installed:";
+echo " - rename";
 echo " - sponge (in package moreutils)";
 echo " - latexpand";
 echo " - de-macro";
@@ -29,7 +32,7 @@ echo "";
 echo " - output .tex file is written to paper4arxiv/flattened.tex";
 echo "";
 echo " author: Thorben Casper";
-echo " date: October 2016";
+echo " created in October 2016";
 }
 
 VERSION=0.0.1
@@ -57,9 +60,10 @@ done
 # --- Compatibility -----------------------------------------------------------------------------------------
 
 # check installed software
-hash sponge 2>/dev/null || { echo >&2 "I require sponge but it's not installed.  Aborting."; exit 1; }
-hash latexpand 2>/dev/null || { echo >&2 "I require latexpand but it's not installed.  Aborting."; exit 1; }
-hash de-macro 2>/dev/null || { echo >&2 "I require de-macro but it's not installed.  Aborting."; exit 1; }
+hash rename 2>/dev/null    || { echo >&2 "I require rename but it's not installed. Aborting.";    exit 1; }
+hash sponge 2>/dev/null    || { echo >&2 "I require sponge but it's not installed. Aborting.";    exit 1; }
+hash latexpand 2>/dev/null || { echo >&2 "I require latexpand but it's not installed. Aborting."; exit 1; }
+hash de-macro 2>/dev/null  || { echo >&2 "I require de-macro but it's not installed. Aborting.";  exit 1; }
 
 # --- Parsing input -----------------------------------------------------------------------------------------
 
@@ -72,20 +76,43 @@ FIGS=$3
 # define directory for source files
 SRC="$(dirname "$(readlink -f "$0")")/src"
 
-# settings
-flattened='flattened' # main .tex file for the paper4arxiv directory
+# define directory for destination files
+DEST=paper4arxiv
 
-# move all required source files from paper directory to new paper4arxiv directory
-mkdir paper4arxiv
-cp -t paper4arxiv *.tex *.sty *.cls *.clo *.bib 2>>/dev/null
-find . -name '*.sty' -print0 | xargs -0 cp -t paper4arxiv
-cp -r $FIGS/ paper4arxiv 2>>/dev/null
-cp -r figsStandalone/ paper4arxiv 2>>/dev/null
-cp -r tabs/ paper4arxiv 2>>/dev/null
-cd paper4arxiv
+# settings
+flattened='flattened' # main .tex file for the $DEST directory
+
+# remove $DEST directory after receiving user confirmation
+if [ -d $DEST ]; then
+    echo -n "Do you want to delete the entire '$DEST' directory [y/n]? "
+    read answer
+    if [ $answer == "y" ]; then
+        rm -r $DEST
+    else
+        echo "$0 requires to delete $DEST before execution. Please rename or move it to a different place."
+        exit 1;
+    fi
+fi
+
+# check whether any duplicate .sty files are present in the tree below the current directory
+DUPLICATES=$(find . -type f -name "*.sty" | sed 's#.*/##' | sort |  uniq -d)
+if [ ! -z "$DUPLICATES" ]; then
+    printf "ERROR: There must be no duplicate .sty-files in the tree below the current directory. Duplicates found:\n $DUPLICATES\n"
+    printf "exiting ...\n"
+    exit 1;
+fi
+
+# move all required source files from paper directory to new $DEST directory
+mkdir $DEST
+cp -t $DEST *.tex *.cls *.clo *.bib 2>>/dev/null
+find . -name '*.sty' -print0 | xargs -0 cp -t $DEST
+cp -r $FIGS/ $DEST 2>>/dev/null
+cp -r figsStandalone/ $DEST 2>>/dev/null
+cp -r tabs/ $DEST 2>>/dev/null
 
 # flatten the latex code using latexpand and keep comments to subsequently flatten bib
-latexpand --keep-comments $TEXFILE.tex > $flattened.tmp
+latexpand --keep-comments $TEXFILE.tex > $DEST/$flattened.tmp
+cd $DEST
 rm *.tex
 mv $flattened.tmp $flattened.tex
 
@@ -123,7 +150,7 @@ rm temf*-private.sty $PKGPREFIX-*-private.sty
 # flatten colors (not supported right now)
 #flattenColors $flattened.tex
 
-# clean not used standalone, todonotes, pgfplots, circui(tikz), graphicspath and tikzexternalize settings
+# remove not used standalone, todonotes, pgfplots, circui(tikz), graphicspath and tikzexternalize settings
 sed -i '/\\usepackage\[\?.*\]\?{standalone}/d' $flattened.tex
 sed -i '/\\usepackage\[\?.*\]\?{todonotes}/d' $flattened.tex
 sed -i '/\\usepackage\[\?.*\]\?{pgfplots}/d' $flattened.tex
@@ -134,6 +161,9 @@ sed -i '/\\graphicspath{{/d' $flattened.tex
 sed -i '/\\usepgfplotslibrary{external}/d' $flattened.tex
 sed -i '/\\tikzexternalize\[/d' $flattened.tex
 
+# remove any \let\xxx\undefined lines
+sed -i '/\\let.*\\undefined/d' $flattened.tex
+
 # remove any consecutive blank lines
 cat -s $flattened.tex | sponge $flattened.tex 
 
@@ -141,11 +171,13 @@ cat -s $flattened.tex | sponge $flattened.tex
 cd $FIGS
 mkdir tmp
 mv -t tmp fig*.pdf fig*.eps fig*.png fig*.jpg 2>>/dev/null
-rm ./* 2>>/dev/null
-mv tmp/* . 2>>/dev/null
-rmdir tmp
+mv tmp ..
+rm -r ./* 2>>/dev/null
+mv ../tmp/* . 2>>/dev/null
+rmdir ../tmp
 rm *eps-converted-to.pdf 2>>/dev/null
 cd ..
+
 # clean up figsStandalone directory
 if [ -d figsStandalone ]; then
     cd figsStandalone 2>>/dev/null
@@ -159,7 +191,7 @@ if [ -d figsStandalone ]; then
     rmdir figsStandalone 2>>/dev/null
 fi
 
-# clean up paper4arxiv directory
+# clean up $DEST directory
 rm ${flattened}_bib.tex *.suc *.syc *.upa *.upb *.aux *.auxlock *.log *.pdf *.bcf *.run.xml *.blg *.out 2>>/dev/null
 rm -r tabs
 
@@ -167,7 +199,7 @@ rm -r tabs
 echo "#!/bin/bash" >> compile
 echo "pdflatex "$flattened.tex >> compile
 echo "pdflatex "$flattened.tex >> compile
-echo "rm *.aux *.log 2>>/dev/null" >> compile
+echo "rm *.out *.aux *.log 2>>/dev/null" >> compile
 chmod +x compile
 
 # execute compile
@@ -175,7 +207,7 @@ chmod +x compile
 
 # write zipme file
 echo "#!/bin/bash" >> zipme
-echo "rm -v "$flattened.zip" 2>>dev/null" >> zipme
+echo "rm -v "$flattened.zip" 2>>/dev/null" >> zipme
 echo "zip" $flattened.zip $flattened.tex $FIGS"/*" >> zipme
 chmod +x zipme
 
